spring:
  data:
    mongodb:
      username: ftmh
      password: ftmh
      host: 27017
      database: customer
      authentication-database: admin

#resilience4j:
#  circuitbreaker:
#    instances:
#      myServiceCircuitBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 5
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10000
#        permittedNumberOfCallsInHalfOpenState: 3
#        eventConsumerBufferSize: 10
server:
  port: 8090