spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: order-service
server:
  port: 8070
