services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - e-commerce_microservices-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    networks:
      - e-commerce_microservices-net
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ftmh
      - MONGO_INITDB_ROOT_PASSWORD=ftmh
    networks:
      - e-commerce_microservices-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ftmh
      ME_CONFIG_BASICAUTH_PASSWORD: ftmh
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ftmh
      ME_CONFIG_MONGODB_ADMINPASSWORD: ftmh
    depends_on:
      - mongodb
    networks:
      - e-commerce_microservices-net

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080 #for UI
      - 1025:1025 #SMTP
networks:
  e-commerce_microservices-net:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:
  mongo: